### PR TITLE
Drop unnecessary dependencies

### PR DESCRIPTION
**Pull request by zmc**
Signed-off-by: Zack Cerza <zack@redhat.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
@zmc cannot test this anymore:
```
Step 3/10 : RUN microdnf update -y &&   microdnf install -y         curl         lsof         python3         python3-pip         python3-setuptools         python3-wheel
 ---> Running in ab205850ec4b

(microdnf:7): librhsm-WARNING **: 21:59:46.598: Found 0 entitlement certificates

(microdnf:7): librhsm-WARNING **: 21:59:46.600: Found 0 entitlement certificates
Downloading metadata...

error: cannot update repo 'ubi-8-baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (28): Timeout was reached for https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi8/8/x86_64/baseos/os/repodata/repomd.xml [Resolving timed out after 30000 milliseconds]
```

**Comment by kshtsk** [comment]
anyways... let's merge it for now

**Review by kshtsk — APPROVED** [review]
lgtm

**Comment by zmc** [comment]
@kshtsk hmm, I can access that just fine - sure you don't have it firewalled? 😉

**Comment by kshtsk** [comment]
> @kshtsk hmm, I can access that just fine - sure you don't have it firewalled?

wonderful, looks like firewall issues... have no idea why default firewall config filters this out...

**Pull request merged**
