### PR TITLE
Fix job details list tree hierarchy

### PR DESCRIPTION
**Pull request by kshtsk**

### CODE REVIEW

**Comment by kshtsk** [comment]
@zmc don't you want to review this ticket?

**Comment by zmc** [comment]
> @zmc don't you want to review this ticket?

Sure, I don't mind at all - just hadn't seen it before. Do you have a screenshot of the fixed UI handy?

**Comment by kshtsk** [comment]
image

**Comment by kshtsk** [comment]
image

**Comment by kshtsk** [comment]
What is new:
-  tasks do not include empty items anymore
- key names are now in bold
- empty values now shown as `(Empty)`
- removed bullets for dictionaries

**Comment by kshtsk** [comment]
@zmc ping

**Review by zmc — APPROVED** [review]

**Pull request merged**
