### PR TITLE
controllers/compare.py: remove urlparse

### PR DESCRIPTION
**Pull request by kamoltat**
Fixes: https://tracker.ceph.com/issues/59299

Signed-off-by: Kamoltat Sirivadhna <ksirivad@redhat.com>

### CODE REVIEW

**Comment by kamoltat** [comment]
To recreate this bug:

start teuthology dev environment following: https://github.com/ceph/teuthology/tree/main/docs/docker-compose

Schedule a job that won't get picked up by dispatcher by using `smithi` as machine, since the docker scripts uses `testnode` as machine.

`teuthology-suite -v --suite-repo https://github.com/ceph/ceph-ci.git  --ceph-repo https://github.com/ceph/ceph-ci.git -c reef --suite upgrade:pacific-x -m smithi --limit 1 --p 50 --force-priority
`
After that, go to link http://localhost:8081/compare/?branch=reef&suite=upgrade:pacific-x

you will get the `urlparse` not defined traceback error

**Comment by kamoltat** [comment]
Validation of this fix: Tested by recreating the bug, apply the fix and it see that the fix works.

**Review by zmc — APPROVED** [review]
Thanks!

**Comment by zmc** [comment]
This change is live

**Pull request merged**
